# Generated by Django 6.0.1 on 2026-01-08 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bounties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('descrition', models.TextField()),
                ('deadline', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('task_type', models.CharField()),
                ('is_assigened', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_amount_transfered', models.BooleanField(default=False)),
                ('is_client_amount_transfered', models.BooleanField(default=False)),
                ('end_date', models.DateField(null=True)),
                ('start_date', models.DateField(null=True)),
                ('status', models.IntegerField(default=0)),
                ('final_submission_link', models.URLField(null=True)),
                ('is_disputed', models.BooleanField(default=False, null=True)),
                ('dispute_end_date', models.DateTimeField(null=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BountyFreelancerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounties')),
            ],
        ),
        migrations.CreateModel(
            name='Chat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('bounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dispute_messages_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('bounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_pera_wallet_address', models.TextField(null=True)),
                ('bounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounties')),
                ('requested_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Voting_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_for', models.TextField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('bounty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bounties.bounties')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
